creat table `user_info`(
 `id` varchar(32) not null,
 `name` varchar(32) not null DEFAULT '',
 `password` varchar(32) not null default '',
 `sex` tinyint(1) default '0' comment '性别，0未知 1男 3女',
 `token` varchar(64) default '' comment 'token',
 `tel` varchar(16) default '' commnet '电话',
 `email` varchar(32) DEFAULT '' comment '邮箱',
 `avatar` varchar(512) DEFAULT '' comment '头像',
 `openid` varchar(64) DEFAULT '' comment '微信openid',
 `qq_id` varchar(64) DEFAULT '' comment 'qq的id',
 `role` tinyint(1) DEFAULT '0' comment '角色 0未知',
 `city` varchar(32) DEFAULT '' comment '城市',
 `experience` tinyint(2) DEFAULT '0' comment '工作经验，0:在校生1:0年 2:1-2年 3:3-5年 4:5-10年 5:10年+ ',
 `skill` varchar(256) DEFAULT '' comment '技能',
 `workday_start_time` INT DEFAULT '' comment '工作日空闲开始时间',
 `workday_ent_time` INT DEFAULT '' comment '工作日空闲结束时间',
 `weekend_start_time` INT DEFAULT '' comment '周末空闲开始时间',
 `weekend_end_time` INT DEFAULT '' comment '周末空闲结束时间',
 `influence` int DEFAULT '0' comment '影响力',
 `line_num` int DEFAULT '0' comment '赞的数量',
 `introduce` varchar(512) DEFAULT '' comment '个人简介',
 `status` tinyint(1) DEFAULT '1' comment `用户状态，0已注销 1正常`,
 `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
 `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
 primary key(`id`)
) comment `用户表`;